// Copyright (c) 2018
// Commonwealth Scientific and Industrial Research Organisation (CSIRO)
// ABN 41 687 119 230
//
// Author: Kazys Stepanas
#ifndef OHMHEIGHTMAP_HEIGHTMAPVOXEL_H
#define OHMHEIGHTMAP_HEIGHTMAPVOXEL_H

#include "OhmHeightmapConfig.h"

#include <cstdint>

namespace ohm
{
/// Voxel layer values for @c HeightmapVoxel::type.
enum HeightmapVoxelLayer : uint8_t
{
  /// A surface (candidate) voxel. For non-layered heightmaps, this is always used. For layered heightmaps this
  /// value is used during construction to indicate there are observations above the voxel. A @c kLayeredFill heightmap
  /// ensure at most one voxel per column is marked as @c kHvlBaseLayer with other voxels marked @c kHvlExtended .
  kHvlBaseLayer = 0,
  /// A layered heightmap voxel could be an extended surface layer. A @c kLayeredFill heightmap marks all bar one voxels
  /// in a column with this value marking the other @c kHvlBaseLayer as a best guess preferred surface. Columns
  /// will not have this value.
  /// @c kHvlExtended if there are no observations above it.
  kHvlExtended,
  kHvlInvalid  ///< Voxel has been determined to be invalid and should be removed.
};

/// Flag values for @c HeightmapVoxel::flags
enum HeightmapVoxelFlag : uint8_t
{
  /// Indicates that the voxel has some amount of clear/free space above it. Most of the time the clearance yields the
  /// same information. However, consider the following figure: (section view)
  ///
  /// @code{.unparsed}
  ///
  ///              --------     surface B
  ///             /
  ///            /
  /// ----------------------    surface A
  /// @endcode
  ///
  /// Where surface A lies below surface B, the voxels will have an appropriate clearance value. However, surface B
  /// may have a zero clearance value - no known obstructions - when there are no observations above if. This can occur
  /// in an outdoor setting as a sky generates no returns.
  ///
  /// If surface B is properly observed, then we can expect some free voxels above each surface occupied voxel which are
  /// generated by the sensor rays coming from above to make those observations. However, this may fail at very shallow
  /// angles of incidence.
  ///
  /// Note this flag is only assessed to a limited range above the heighmap voxel, limited by the heightmap ceiling
  /// range.
  kHvfObservedAbove = (1 << 0)
};

/// A voxel within the heightmap.
///
/// @note Use of @c alignas will need to be removed should this structure be needed in GPU code. OpenCL 1.2 supports
/// `__attribute__ ((aligned (n)))` style alignment. A macro may be used to manage this.
/// See https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/
///
/// CUDA compatibility would also need to be assessed.
struct ohmheightmap_API alignas(8) HeightmapVoxel
{
  /// The name of the layer which stores these voxels.
  static const char *const kHeightmapLayer;
  /// The name of the layer used to build the first pass heightmap. This is the layer without blur.
  /// Only used when using blur.
  static const char *const kHeightmapBuildLayer;

  /// The voxel height, relative to the voxel centre.
  float height;
  /// Clearance above the voxel height to the next, occupied voxel. Zero indicates no known overhead obstruction.
  float clearance;
  /// Local surface normal X coordinate.
  ///
  /// The three normal coordinates are only valid when the heightmap has been generated from an occupancy map
  /// which includes @c CovarianceVoxel . The normal is an estimate from the covariance.
  float normal_x;
  /// Local surface normal Y coordinate.
  float normal_y;
  /// Local surface normal Z coordinate.
  float normal_z;
  /// Layer information. Currently restricted to values of @c HeightmapVoxelLayer.
  uint8_t layer;
  /// Alignment padding to add @c contributing_samples without changing the data structure.
  uint8_t flags;
  /// The number of samples in the source voxel which contributed to this result - only available if @c VoxelMean
  /// is available to accumulate the sample count. Note that this may be lower than the value in @c VoxelMean
  /// because it is of lower precision. In this case, the value is set to @c 0xffffu.
  uint16_t contributing_samples;
};
}  // namespace ohm

#endif  // OHMHEIGHTMAP_HEIGHTMAPVOXEL_H
